Categories front feature
danielh27/project-dbs pull request #15
Opened 2023-08-28 21:42 UTC by SekiroXtreme

## Descripción

Este pull request introduce los siguientes cambios:

- Se ha añadido un carrusel en la interfaz de usuario utilizando la librería SwiperJS.
- Se ha actualizado el nombre del archivo "application.scss" principal del proyecto a "application_styles.scss".
- Las tarjetas de la vista ahora utilizan información de la base de datos en lugar de información estática.

## Capturas de Pantalla
| Mobile | Tablet | Laptop |
| --------- | -------- | --------- |
|     ![carousel_mobile-view](https://github.com/danielh27/project-dbs/assets/109052525/e35a85a7-80ee-43ca-a579-95259ab0a6eb)     |    ![carousel_tablet-view](https://github.com/danielh27/project-dbs/assets/109052525/02724f25-fd48-41ca-9e85-93ecfdf253db)     |    ![carousel_laptop-view](https://github.com/danielh27/project-dbs/assets/109052525/9ce8b2fb-f7fe-4345-9296-b8211db69e0d)     |

## Notas Adicionales

- El carrusel está sujeto a cambios futuros(cantidad de cards, tamaño, entre otros).

2023-08-29 04:30 UTC, SegundoRP commented
I think we shouldnt change the conventional name application.scss, if it is not annoying change it, it would be good. The rest its good

2023-08-29 04:30 UTC, SegundoRP approved these changes

2023-09-04 20:33 UTC, danielh27 requested changes

2023-09-04 20:33 UTC, danielh27 commented on yarn-error.log
Este archivo no se sube, es de tu local

2023-09-04 20:33 UTC, danielh27 commented on install.sh
esto de que es?

2023-09-05 15:12 UTC, danielh27 approved these changes

2023-09-05 15:12 UTC, merged