Sr/Recently services
danielh27/project-dbs pull request #22
Opened 2024-04-20 21:17 UTC by SegundoRP

Services Index - Visitados recientemente por usuario

2024-04-23 04:46 UTC, SekiroXtreme approved these changes

2024-04-23 04:52 UTC, danielh27 requested changes

2024-04-23 04:52 UTC, danielh27 commented on app/controllers/services_controller.rb
> +    @your_recently_services = current_user&.visited_services
creo que la variable seria mejor nombrarla @services_recently_visited o algo por el estilo, sin el "your"

2024-04-23 04:52 UTC, danielh27 commented on app/controllers/services_controller.rb
> +    current_user&.recently_visited_services&.prepend(@service.id)
esta linea para que es?

2024-04-23 04:52 UTC, danielh27 commented on app/models/user.rb
> +    recently_visited_services.elements.map { |id| Service.find(id.to_i) }
esto pareciera que fuese a ejecutar una query por cada ID, si no es es asi ignora este comment xD

si no, la query deberia buscar todos los ID en una sola consulta

2024-04-24 04:54 UTC, SegundoRP commented on app/models/user.rb
> +    recently_visited_services.elements.map { |id| Service.find(id.to_i) }
lesto!

2024-04-24 04:55 UTC, SegundoRP commented on app/controllers/services_controller.rb
> +    @your_recently_services = current_user&.visited_services
lesto!

2024-04-30 06:36 UTC, danielh27 approved these changes

2024-05-04 20:42 UTC, merged